--- # Start
name: 0cherry/openssl

# 유저의 github 저장소 정보
url: https://github.com/0cherry/openssl.git

docker-image: 

# predefined docker-image를 사용하되, 추가적인 설정이 필요한 경우 이렇게 정의
extra-build-env-setting-commands: 

test-build-command: | # 테스트 빌드 커맨드 / defect4cpp 기준 meta.json의 내용이 필요
  ./config enable-unit-test
  make clean
  make -j8 depend
  make -j8

coverage-build-command: | # 커버리지 빌드 커맨드 / defect4cpp 기준 meta.json의 내용이 필요(SBFL: gcov)
  ./config CFLAGS=\"--coverage -g -O0\" LDFLAGS=\"-lgcov\" enable-unit-test
  make clean
  make -j@DPP_PARALLEL_BUILD@ depend
  make -j8

# 테스트 type이 문제: gtest의 경우 원하는 테스트를 실행할 수 있으니 문제가 없음
# 그렇지 않으면 test-case에 실행할 테스트 번호를 range로 하도록함
# 테스트 실행 역시 range안에 있는 테스트들만 실행하도록 묶어서 command를 부르거나 여러번 불러야함
test-type: custom
test-case: [0-5, 8-10]

test-command: | # 테스트 실행
  bash -c '[ -f AUTOMAKE_TEST_CASE.output ] || make list-tests | grep test_ > AUTOMAKE_TEST_CASE.output'
  bash -c 'make -j8 test

test-coverage-command: | # 커버리지 테스트 실행
  bash -c '[ -f AUTOMAKE_TEST_CASE.output ] || make list-tests | grep test_ > AUTOMAKE_TEST_CASE.output'
  bash -c 'make CFLAGS=\"--coverage -O0 -g -DDPP_ENABLE_GCOV\" LDFLAGS=\"-lgcov\" -j8 test'
