# /.github/workflows/test-0cherry-github-action.yml
name: Github Action Test

on:
  workflow_dispatch:
  # push

jobs:
  vulcan:
    runs-on: self-hosted

    steps:
      - name: Test vulcan action
        uses: Suresoft-GLaDOS/vulcan-action@test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
